---
- name: Install
  macos_install:
    app_name: "{{ item.name }}"
    dmg_path: "{{ dmg_path }}/{{ item.name }}.dmg"
    force: "{{ item.force }}"
    installed_name: "{{ item.installed_name }}"
    state: "{{ item.state }}"
  with_items: "{{ dmgs }}"

- name: Cleanup
  file:
    state: "{{ item.dmg_stat | default('absent') }}"
    path: "{{ dmg_path }}/{{ item.name }}.dmg"
  with_items: "{{ dmgs }}"